version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
    - deployml_network
    ports:
    - 5672:5672
    - 5673:5673
    - 15672:15672

  dbserver:
    image: mongo
    container_name: "mongo"
    restart: always
    ports:
    - 27017:27017
    networks:
    - deployml_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  webserver:
    image: ml-jumpstart-kit/webserver
    build: ./WebServer
    ports:
      - 80:80
    networks:
      - deployml_network
    restart: on-failure
    depends_on:
      - rabbitmq
      - dbserver
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=dbserver
      - QUEUE_NAME=ml_queue
    links:
      - rabbitmq

  modelserver_1:
    image: ml-jumpstart-kit/modelserver
    build: ./modelserver
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=dbserver
      - QUEUE_NAME=ml_queue
      - HEART_BEAT_TIMEOUT=120
      - BLOCKED_CONNECTION_TIMEOUT=300
    networks:
      - deployml_network
    depends_on:
      - rabbitmq
    restart: on-failure

  modelserver_2:
    image: ml-jumpstart-kit/modelserver
    build: ./modelserver
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=dbserver
      - QUEUE_NAME=ml_queue
      - HEART_BEAT_TIMEOUT=120
      - BLOCKED_CONNECTION_TIMEOUT=300
    networks:
      - deployml_network
    depends_on:
      - rabbitmq
    restart: on-failure

networks:
    deployml_network:
