version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
    - deployml_network
    ports:
    - 5672:5672
    - 5673:5673
    - 15672:15672

  dbserver:
    image: mongo
    container_name: "mongo"
    restart: always
    ports:
    - 27017:27017
    networks:
    - deployml_network

  webserver:
    image: ml-jumpstart-kit/webserver
    build: ./WebServer
    ports:
      - 8080:80
    networks:
      - deployml_network
    restart: on-failure
    depends_on:
      - rabbitmq
      - dbserver
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=dbserver
      - QUEUE_NAME=ml_queue
    links:
      - rabbitmq

  modelserver:
    image: ml-jumpstart-kit/modelserver
    build: ./modelserver
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=dbserver
      - QUEUE_NAME=ml_queue
      - HEART_BEAT_TIMEOUT=120
      - BLOCKED_CONNECTION_TIMEOUT=300
    networks:
      - deployml_network
    depends_on:
      - rabbitmq
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
    deployml_network:
